### ISSUE TITLE
已有 docekr-compose 为什么有 bug

### ISSUE THREAD

**Issue by starscow** [testnet0/testnet#1]
已有 docekr-compose 为什么有 bug
[TestNet] 未发现 Docker Compose Plugin

**Comment by starscow** [comment]
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 124, in docker_client
    kwargs = kwargs_from_env(environment=environment, ssl_version=tls_version)
TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'
[TestNet] TestNet安装成功，请稍等2分钟打开后台登录...
[TestNet] 后台访问地址：https://0.0.0.0:8099/
[TestNet] https://127.0.0.1:8099/
[TestNet] https://192.168.1.160:8099/
[TestNet] https://172.17.0.1:8099/
[TestNet] https://172.19.0.1:8099/
[TestNet] https://172.20.0.1:8099/
[TestNet] https://172.23.0.1:8099/
root@ubuntu:/home/ubuntu/testnet#

**Comment by testnet0** [comment]
> 已有 docekr-compose 为什么有 bug [TestNet] 未发现 Docker Compose Plugin


可以看下这个：
https://juejin.cn/post/7325132133168988197
